Allow retrieval of 50 ads at a time.
parameter1/fortnight-graph pull request #13
Opened 2022-10-07 13:22 UTC by Shinsina

This blocks more than 10 ads being returned at a time, unsure if there was a reason for this number being set to what it was, open to suggestions regarding if and how this should be changed.

2022-10-07 13:22 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Site: Sessions.hub.heart.org Industry Hightlights Section - Native Ads](https://trello.com/c/UszbF9LE/323-site-sessionshubheartorg-industry-hightlights-section-native-ads)

2022-10-18 15:02 UTC, B77Mills requested changes

2022-10-18 15:02 UTC, B77Mills commented on src/services/campaign-delivery.js
> +    const limit = num > 0 ? parseInt(num, 50) : 1;
@Shinsina This line shouldn't need to change.  The only thing that should change here to increase the max limit is the next line.  `if (limit > 50)`

I believe parseInt(num, 50) will return  NaN no matter what you set num.

2022-10-18 15:44 UTC, B77Mills approved these changes

2022-10-18 18:39 UTC, merged